//  Identifier Profiles
Alias: $COVIDDataID = https://nhdr.gov.ph/fhir/StructureDefinition/COVIDDataID
Alias: $COVIDPatientID = https://nhdr.gov.ph/fhir/StructureDefinition/COVIDPatientID
Alias: $FHUDCode = https://nhdr.gov.ph/fhir/StructureDefinition/DOHfhudCode
Alias: $OtherID = https://nhdr.gov.ph/fhir/StructureDefinition/OtherID
Alias: $PhilHealthID = https://nhdr.gov.ph/fhir/StructureDefinition/PhilHealthID
Alias: $RegistrationNo = https://nhdr.gov.ph/fhir/StructureDefinition/RegistrationNo

//  DataType Profiles
Alias: $SD_MiddleName = https://nhdr.gov.ph/fhir/StructureDefinition/MiddleName
Alias: $SD_Address = https://nhdr.gov.ph/fhir/StructureDefinition/PH-Address
Alias: $SD_HumanName = https://nhdr.gov.ph/fhir/StructureDefinition/PH-HumanName
Alias: $SD_Signature = https://nhdr.gov.ph/fhir/StructureDefinition/PH-Signature

//  Extensions
Alias: $Signature = https://nhdr.gov.ph/fhir/StructureDefinition/ExtSignature
Alias: $SignaturePosition = https://nhdr.gov.ph/fhir/StructureDefinition/SignaturePosition
Alias: $SignatureReason = https://nhdr.gov.ph/fhir/StructureDefinition/SignatureReason
Alias: $SignatureSubType = https://nhdr.gov.ph/fhir/StructureDefinition/SignatureSubType
Alias: $SignatureThumbmark = https://nhdr.gov.ph/fhir/StructureDefinition/SignatureThumbmark

// CodeSystems
Alias: $AllergyIntoleranceClinicalStatusCS = http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical
Alias: $ConditionCategoryCS = http://terminology.hl7.org/CodeSystem/condition-category
// Alias: $ConditionClinicalStatusCS = http://terminology.hl7.org/CodeSystem/condition-clinical|4.0.1
Alias: $ConditionSeverityCS = http://terminology.hl7.org/CodeSystem/v2-0421
Alias: $ConditionVerificationStatusCS = http://terminology.hl7.org/CodeSystem/condition-ver-status
Alias: $ContactEntityTypeCS = http://terminology.hl7.org/CodeSystem/contactentity-type
Alias: $ContactRelationshipCS = http://terminology.hl7.org/CodeSystem/v2-0131
Alias: $CoverageClassCS = http://terminology.hl7.org/CodeSystem/coverage-class
Alias: $CoverageCopayTypeCS = http://terminology.hl7.org/CodeSystem/coverage-copay-type
Alias: $CoverageCopayTypeLocalCS = https://nhdr.gov.ph/fhir/CodeSystem/CoverageCopayTypeLocalCS
Alias: $DiagnosticServiceSectionCS = http://terminology.hl7.org/CodeSystem/v2-0074|4.0.1
Alias: $DischargeDispositionCS = http://terminology.hl7.org/CodeSystem/discharge-disposition
Alias: $DrugCodesCS = https://verification.fda.gov.ph //FDA Website
Alias: $EncounterClassificationCS =  http://terminology.hl7.org/CodeSystem/v3-ActCode
Alias: $EncounterTypeCS = http://terminology.hl7.org/CodeSystem/encounter-type
Alias: $FacilityMajorTypeCS = https://nhdr.gov.ph/fhir/CodeSystem/FacilityMajorTypeCS
Alias: $GenderCS = http://hl7.org/fhir/administrative-gender
Alias: $ICD10CS = http://hl7.org/fhir/sid/icd-10 //ICD Link
Alias: $IdentifierType = http://terminology.hl7.org/CodeSystem/v2-0203
Alias: $ImmunizationRouteCS = http://terminology.hl7.org/CodeSystem/v3-RouteOfAdministration
Alias: $ImmunizationStatusCS = http://hl7.org/fhir/event-status
Alias: $ImmunizationStatusReasonCS = http://terminology.hl7.org/CodeSystem/v3-ActReason
Alias: $ImmunizationVaccineCodeCS = https://nhdr.gov.ph/fhir/CodeSystem/ImmunizationVaccineCodeCS
Alias: $IndigenousGroupCS = https://nhdr.gov.ph/fhir/CodeSystem/IndigenousGroupCS
Alias: $LhioCS = https://nhdr.gov.ph/fhir/CodeSystem/LhioCS
Alias: $LocationPhysicalTypeCS = http://terminology.hl7.org/CodeSystem/location-physical-type|4.0.1
Alias: $LOINC = http://loinc.org
Alias: $MedicationAdministrationStatusCS = http://terminology.hl7.org/CodeSystem/medication-admin-status
Alias: $MemberTypeCS = https://nhdr.gov.ph/fhir/CodeSystem/MemberTypeCS
Alias: $NHFRCS = https://nhfr.doh.gov.ph/VActivefacilitiesList
Alias: $NullFlavorCS =  http://terminology.hl7.org/CodeSystem/v3-NullFlavor
Alias: $ObservationCategoryCS = http://terminology.hl7.org/CodeSystem/observation-category
Alias: $ObservationInterpretationCS = http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation
Alias: $ObservationMethodCS = http://terminology.hl7.org/CodeSystem/v3-ObservationMethod
Alias: $ObservationValueCS = https://nhdr.gov.ph/fhir/CodeSystem/ObservationValueCS
Alias: $OrganizationTypeCS = http://terminology.hl7.org/CodeSystem/organization-type|4.0.1
Alias: $OrganizationTypeLocalCS = https://nhdr.gov.ph/fhir/CodeSystem/OrganizationTypeLocalCS
Alias: $OwnershipMajorClassificationCS = https://nhdr.gov.ph/fhir/CodeSystem/OwnershipMajorClassificationCS
Alias: $PatientTypeCS = https://nhdr.gov.ph/fhir/CodeSystem/PatientTypeCS
Alias: $PractitionerRoleCS = http://terminology.hl7.org/CodeSystem/practitioner-role
Alias: $ProCS = https://nhdr.gov.ph/fhir/CodeSystem/ProCS
Alias: $ProcedureStatusCS = http://hl7.org/fhir/event-status
Alias: $ProcedureOutcomeCS = http://terminology.hl7.org/CodeSystem/v2-0241
// Alias: $PSGCCS = https://nhdr.gov.ph/fhir/CodeSystem/PSGCCS
Alias: $PSCEDCS = https://psa.gov.ph/classification/psced/level
Alias: $PSGCCS = https://psa.gov.ph/classification/psgc //PSA Website
Alias: $PSOCCS = https://psa.gov.ph/classification/psoc/unit //PSA Website (PSOC)
Alias: $ReasonMedicationGivenCS = http://terminology.hl7.org/CodeSystem/reason-medication-given
Alias: $RoleCodeCS = http://terminology.hl7.org/CodeSystem/v3-RoleCode
Alias: $RVSCodeCS = https://nhdr.gov.ph/fhir/CodeSystem/RVSCodeCS
Alias: $SexCS = http://terminology.hl7.org/CodeSystem/v2-0001
Alias: $SNOMED = http://snomed.info/sct
Alias: $ServiceRequestStatusCS = http://hl7.org/fhir/request-status
Alias: $ServiceTypeCS = http://terminology.hl7.org/CodeSystem/service-type
Alias: $SpecimenConditionCS = http://terminology.hl7.org/CodeSystem/v2-0493
Alias: $SpecimenProcessingProcedureCS = http://terminology.hl7.org/CodeSystem/v2-0373
Alias: $SpecimenTypeCS = http://terminology.hl7.org/CodeSystem/v2-0487
Alias: $ObservationInterpretationCS = http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation
Alias: $ObservationCategoryCS = http://terminology.hl7.org/CodeSystem/observation-category


// ValueSets
Alias: $AllergyIntoleranceCategoryVS = http://hl7.org/fhir/allergy-intolerance-category
Alias: $AllergyIntoleranceReactionSeverityVS = http://hl7.org/fhir/reaction-event-severity
Alias: $AppointmentStatusVS = http://hl7.org/fhir/appointmentstatus // check the local references and the forms, as the forms only use Y or N
Alias: $ConditionClinicalStatusVS = http://hl7.org/fhir/ValueSet/condition-clinical
Alias: $DiagnosticReportStatusVS = http://hl7.org/fhir/diagnostic-report-status
Alias: $EducationalAttainmentVS = https://nhdr.gov.ph/fhir/ValueSet/EducationalAttainmentVS
Alias: $EncounterStatus = http://hl7.org/fhir/encounter-status
Alias: $ICD10VS = https://nhdr.gov.ph/fhir/ValueSet/ICD10VS
Alias: $ImmunizationOriginVS = http://hl7.org/fhir/ValueSet/immunization-origin
Alias: $MaritalStatusVS = http://hl7.org/fhir/ValueSet/marital-status
Alias: $MedicationFormVS = http://terminology.hl7.org/ValueSet/v3-OrderableDrugForm
Alias: $MedicationRouteVS = http://terminology.hl7.org/ValueSet/v3-RouteByMethod
Alias: $MedicationStatusVS = http://hl7.org/fhir/ValueSet/medication-statement-status
Alias: $MemberTypeVS = https://nhdr.gov.ph/fhir/ValueSet/MemberTypeVS
Alias: $PatientTypeVS = https://nhdr.gov.ph/fhir/ValueSet/PatientTypeVS
Alias: $Nationality = http://hl7.org/fhir/StructureDefinition/patient-nationality|5.2.0
Alias: $ObservationMethodVS = https://nhdr.gov.ph/fhir/ValueSet/ObservationMethodVS
Alias: $ObservationStatusVS = http://hl7.org/fhir/observation-status
Alias: $OrganizationTypeVS = https://nhdr.gov.ph/fhir/ValueSet/OrganizationTypeVS
Alias: $ProvinceVS = https://nhdr.gov.ph/fhir/ValueSet/ProvinceVS
Alias: $RaceVS = http://terminology.hl7.org/ValueSet/v3-Race
Alias: $ReligionVS = http://terminology.hl7.org/ValueSet/v3-ReligiousAffiliation    // CS_Religion exists but not merged or used yet
Alias: $ServiceRequestStatusVS = https://nhdr.gov.ph/fhir/ValueSet/ServiceRequestStatusVS
Alias: $SexVS = https://nhdr.gov.ph/fhir/ValueSet/SexVS
Alias: $SpecimenCollectionMethodVS = https://nhdr.gov.ph/fhir/ValueSet/SpecimenCollectionMethodVS
Alias: $YesNoVS = http://terminology.hl7.org/ValueSet/v2-0136
Alias: $OccupationClassificationVS = https://nhdr.gov.ph/fhir/ValueSet/OccupationClassificationVS
Alias: $ServiceTypeVS = https://nhdr.gov.ph/fhir/ValueSet/ServiceTypeVS