Alias: $PH_Address = https://nhdr.gov.ph/fhir/StructureDefinition/PH-Address
Alias: $YesNo = http://terminology.hl7.org/CodeSystem/v2-0532
Alias: $YesNoValueSet = http://terminology.hl7.org/ValueSet/v2-0136
Alias: $ClinicalStatusValueSet = https://nhdr.gov.ph/fhir/ValueSet/ClinicalStatusValueSet
Alias: $OrganizationType = https://nhdr.gov.ph/fhir/ValueSet/OrganizationType
Alias: $MiddleName = https://nhdr.gov.ph/fhir/StructureDefinition/MiddleName
Alias: $PH_HumanName = https://nhdr.gov.ph/fhir/StructureDefinition/PH-HumanName
Alias: $IndigenousGroupValueSet = https://nhdr.gov.ph/fhir/ValueSet/IndigenousGroupValueSet
Alias: $MaritalStatusValueSet = http://hl7.org/fhir/ValueSet/marital-status

// These aliases below haven't been properly checked yet for any possible simplification, fixes or removal
Alias: $ConditionBodySiteCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/ConditionBodySiteCodeSystem
Alias: $ConditionCategoryCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/ConditionCategoryCodeSystem
Alias: $ConditionCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/ConditionCodeSystem
Alias: $ConditionSeverityCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/ConditionSeverityCodeSystem
Alias: $ConditionVerificationStatusCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/ConditionVerificationStatusCodeSystem
Alias: $contact-relationship-codes = https://nhdr.gov.ph/fhir/contact-relationship-codes
Alias: $DiagnosticReportCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/DiagnosticReportCodeSystem
Alias: $EncounterDischargeDisposition = https://nhdr.gov.ph/fhir/CodeSystem/EncounterDischargeDisposition
Alias: $encounter-location-physical-type = https://nhdr.gov.ph/fhir/encounter-location-physical-type
Alias: $encounter-service-type-codes = https://nhdr.gov.ph/fhir/encounter-service-type-codes
Alias: $encounter-type-codes = https://nhdr.gov.ph/fhir/encounter-type-codes
Alias: $ImmunizationStatusCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/ImmunizationStatusCodeSystem
Alias: $ImmunizationStatusReasonCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/ImmunizationStatusReasonCodeSystem
Alias: $ImmunizationVaccineCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/ImmunizationVaccineCodeSystem
Alias: $ImmunizationReportOriginCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/ImmunizationReportOriginCodeSystem
Alias: $ImmunizationRouteCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/ImmunizationRouteCodeSystem
Alias: $indigenous-group-codes = https://nhdr.gov.ph/fhir/indigenous-group-codes
Alias: $marital-status-codes = https://nhdr.gov.ph/fhir/marital-status-codes
Alias: $MedicalAdministrationStatusCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/MedicalAdministrationStatusCodeSystem
Alias: $ObservationMethodCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/ObservationMethodCodeSystem
Alias: $ObservationValueCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/ObservationValueCodeSystem
// Alias: $organization-type-codes = https://nhdr.gov.ph/fhir/organization-type-codes
Alias: $practitioner-role-codes = https://nhdr.gov.ph/fhir/practitioner-role-codes
Alias: $ProcedureBodySiteCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/ProcedureBodySiteCodeSystem
Alias: $ProcedureCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/ProcedureCodeSystem
Alias: $ProcedureStatusCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/ProcedureStatusCodeSystem
// Alias: $sex-codes = https://nhdr.gov.ph/fhir/sex-codes
Alias: $SpecimenCollectionMethodCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/SpecimenCollectionMethodCodeSystem
Alias: $SpecimenConditionCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/SpecimenConditionCodeSystem
Alias: $SpecimenProcessingProcedureCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/SpecimenProcessingProcedureCodeSystem
Alias: $SpecimenTypeCodeSystem = https://nhdr.gov.ph/fhir/CodeSystem/SpecimenTypeCodeSystem
Alias: $loinc = http://loinc.org
// Alias: $cqf-calculatedValue = http://hl7.org/fhir/StructureDefinition/cqf-calculatedValue
// Alias: $patient-nationality = http://hl7.org/fhir/StructureDefinition/patient-nationality
// Alias: $patient-religion = http://hl7.org/fhir/StructureDefinition/patient-religion
// Alias: $SexValueSet = https://nhdr.gov.ph/fhir/ValueSet/SexValueSet
// Alias: $EncounterIllnessClassValueSet = https://nhdr.gov.ph/fhir/StructureDefinition/EncounterIllnessClassValueSet
// Alias: $IndigenousPeopleValueSet = https://nhdr.gov.ph/fhir/ValueSet/IndigenousPeopleValueSet
// Alias: $psoc = https://psa.gov.ph/classification/psoc
// Alias: $psgc = http://psgc.psa.gov.ph
// Alias: $ExtAddress = https://nhdr.gov.ph/fhir/StructureDefinition/ExtAddress
