ValueSet: ConditionVerificationStatusValueSet
Id: ConditionVerificationStatusValueSet
Title: "Condition Verification Status Value Set"
Description: "A value set representing verification status codes for conditions, particularly for diseases like JE, measles, rubella, polio, and others."
* ^url = "https://nhdr.gov.ph/fhir/ValueSet/ConditionVerificationStatusValueSet"
* ^version = "1.0.0"
* ^status = #draft
* ^experimental = false
* ^date = "2024-11-28"
* ^publisher = "NHDR"
* $ConditionVerificationStatusCodeSystem#Suspect "Suspect"
* $ConditionVerificationStatusCodeSystem#Probable "Probable"
* $ConditionVerificationStatusCodeSystem#Confirmed "Confirmed"
* $ConditionVerificationStatusCodeSystem#NonCovid19Case "Non Covid-19 Case"
* $ConditionVerificationStatusCodeSystem#LaboratoryConfirmedJE "Laboratory confirmed JE"
* $ConditionVerificationStatusCodeSystem#JE "JE"
* $ConditionVerificationStatusCodeSystem#AESOtherAgent "AES other agent"
* $ConditionVerificationStatusCodeSystem#AESUnknown "AES unknown"
* $ConditionVerificationStatusCodeSystem#LaboratoryConfirmedMeasles "Laboratory Confirmed Measles"
* $ConditionVerificationStatusCodeSystem#EpiLinkedConfirmedMeasles "Epi-linked Confirmed Measles"
* $ConditionVerificationStatusCodeSystem#MeaslesCompatible "Measles Compatible"
* $ConditionVerificationStatusCodeSystem#LaboratoryConfirmedRubella "Laboratory Confirmed Rubella"
* $ConditionVerificationStatusCodeSystem#EpiLinkedConfirmedRubella "Epi-linked Confirmed Rubella"
* $ConditionVerificationStatusCodeSystem#DiscardedNonMeaslesRubella "Discarded Non Measles/Rubella"
* $ConditionVerificationStatusCodeSystem#ConfirmedWildPolio "Confirmed wild polio"
* $ConditionVerificationStatusCodeSystem#VaccineDerivedParalyticPolio "Vaccine-derived paralytic polio (VDPV)"
* $ConditionVerificationStatusCodeSystem#VaccineAssociatedParalyticPolio "Vaccine-associated paralytic polio (VAPP)"
* $ConditionVerificationStatusCodeSystem#RecipientVAPP "Recipient VAPP"
* $ConditionVerificationStatusCodeSystem#ContactVAPP "Contact VAPP"
* $ConditionVerificationStatusCodeSystem#PolioCompatible "Polio compatible"
* $ConditionVerificationStatusCodeSystem#DiscardedAsNonPolio "Discarded as Non-Polio"
* $ConditionVerificationStatusCodeSystem#Laboratory "Laboratory"
* $ConditionVerificationStatusCodeSystem#LostToFollowUp "Lost to follow-up"
* $ConditionVerificationStatusCodeSystem#Death "Death"
* $ConditionVerificationStatusCodeSystem#WithResidualParalysis "With residual paralysis"
* $ConditionVerificationStatusCodeSystem#WithoutResidualParalysis "Without residual paralysis"
* $ConditionVerificationStatusCodeSystem#LabConfirmed "Lab Confirmed"
* $ConditionVerificationStatusCodeSystem#EpiLinked "EPI linked"
* $ConditionVerificationStatusCodeSystem#ClinicallyCompatible "Clinically compatible"
* $ConditionVerificationStatusCodeSystem#Discarded "Discarded"