ValueSet: SpecimenProcessingProcedure
Id: SpecimenProcessingProcedure
Title: "Specimen Processing Procedure Value Set"
Description: "A value set representing various specimen processing procedures."
* ^url = "https://nhdr.gov.ph/fhir/ValueSet/SpecimenProcessingProcedure"
* ^version = "1.0.0"
* ^status = #draft
* ^experimental = false
* ^date = "2024-11-28"
* ^publisher = "NHDR"
* $SpecimenProcessingProcedureCodeSystem#ELISA "Enzyme-linked Immunoassay (ELISA)"
* $SpecimenProcessingProcedureCodeSystem#IgGAntibodyTest "IgG Antibody Test"
* $SpecimenProcessingProcedureCodeSystem#IgMandIgGAntibodyTest "IgM and IgG Antibody Test"
* $SpecimenProcessingProcedureCodeSystem#VirusAntigenDetection "Virus Antigen Detection (NS1)"
* $SpecimenProcessingProcedureCodeSystem#CompleteBloodCount "Complete Blood Count"
* $SpecimenProcessingProcedureCodeSystem#IGG-IgMAntibodyTest "IGG-IgM Antibody Test"
* $SpecimenProcessingProcedureCodeSystem#IGM-IgGAntibodyTest "IGM-IgG Antibody Test"
* $SpecimenProcessingProcedureCodeSystem#PCR "Polymerase Chain Reaction"
* $SpecimenProcessingProcedureCodeSystem#VirusIsolation "Virus Isolation"
* $SpecimenProcessingProcedureCodeSystem#CultureAndSensitivity "Culture and Sensitivity"
* $SpecimenProcessingProcedureCodeSystem#WidalsTest "Widals Test"
* $SpecimenProcessingProcedureCodeSystem#TyphidotTest "Typhidot Test"
* $SpecimenProcessingProcedureCodeSystem#TubexTest "Tubex Test"
* $SpecimenProcessingProcedureCodeSystem#DirectFluorescentAntibodyTest "Direct Fluorescent Antibody Test (FAT)"
* $SpecimenProcessingProcedureCodeSystem#RapidAntigenTest "Rapid Antigen Test"
* $SpecimenProcessingProcedureCodeSystem#MicroscopicAgglutinationTest "Microscopic Agglutination Test"
* $SpecimenProcessingProcedureCodeSystem#RapidDiagnosticTest "Rapid Diagnostic Test"
* $SpecimenProcessingProcedureCodeSystem#Culture "Culture"
* $SpecimenProcessingProcedureCodeSystem#LatexAgglutination "Latex agglutination"
* $SpecimenProcessingProcedureCodeSystem#GramStain "Gram stain"
* $SpecimenProcessingProcedureCodeSystem#CultureAndPCR "Culture and PCR"